### ISSUE TITLE
Componente não visualiza o dropdown

### ISSUE THREAD

**Issue by davidjuniors** [tiagomatosweb/vue-autocomplete#1]
Oi, bom dia Tiago,

Cara, esse componente de autocomplete, é exatamente o que estou precisando em meu projeto, porém não consigo implementa-lo...

O Dropdown com as informações não aparece nada (embora o retorno json esteja ok), e também as vezes me tira esse erro no console log.
Uncaught (in promise) TypeError: _this2.$set is not a function

Estou usando Laravel + Vue3

Poderia me ajudar com esse tema?

Abs.

**Comment by tiagomatosweb** [comment]
Cara, esse componente foi feito para o Vue 2 para efeito de estudo via YouTube, e por isso vai dá bug no Vue 3.

**Comment by davidjuniors** [comment]
Olá Tiago

Entendido, realmente uma pena, é um ótimo componente, e realmente útil... Por favor, considere fazê-lo também para Vue3.

Eu consigo fazer funcionar em meu projeto, cancelando a função highlightOptions()

Abs.

**Comment by tiagomatosweb** [comment]
Vou pensar nisso pois o objetivo foi mesmo para efeitos de estudo dos alunos do yourube.

Quem sabe eu faça uma outra serie transformando para Vue 3.
